var lang = {
    en: {
        yes: 'Yes',
        no: 'No',
        confirmation: 'Confirmation',
        name_required: 'Name is required',
        email_required: 'Email is required',
        email_invalid: 'Email is invalid',
        password_required: 'Password is required',
        password_old_required: 'Old password is required',
        message: 'Message',
        login: 'Login',
        email: 'Email',
        password: 'Password',
        there_was_an_error: 'There was an error when loading data',
        are_sure_to_logout: 'Are you sure that want logout ?',
        today: 'Today',
        all: 'All',
        welcome: 'Welcome',
        meetings: 'My Meetings',
        profile: 'Profile',
        back: 'Back',
        call_to: 'Call',
        send_email: 'Send email',
        acceso_socios: 'MEMBER ACCESS',
        login_msg1: 'Enter the email you used <br> in the registry.',
        login_msg2: 'WARNING you can only use your <br> subscription on a device',
        no_socios: 'NO PARTNERS',
        login_msg3: 'I am not yet a member, but <br> I want to enter <br> as a guest and see the discounts',
        invitado: 'GUEST',
        entrar: 'ENTER',
        login_email_required: 'Email is required',
        login_email_invalid: 'Email is invalid',
        nombre: 'Name',
        apellido: 'Surename',
        Email: 'Email',
        tarjeta: 'Card Number',
        cvc: 'CVV',
        mes: 'Month',
        ano: 'Year',
        enviar: 'SEND',
        acepto: 'Accept terms and condicions',
        register_header: 'REGISTER FORM <br> Fill this form for enter <br> in the most exclusive club of discounts',
        renew_header: 'PAYMENT FORM <br> Fill this form for continue in <br> the most exclusive club of discounts',
        login_nombre_required: 'Name is required',
        login_apellido_required: 'Surename is required',
        login_tarjeta_required: 'Tarjeta is required',
        login_mes_required: 'Month is required',
        login_ano_required: 'Year is required',
        login_acepto_required: 'You must accept terms and conditions',
        months: [
            {id: 1, name: 'January'},
            {id: 2, name: 'February'},
            {id: 3, name: 'March'},
            {id: 4, name: 'April'},
            {id: 5, name: 'May'},
            {id: 6, name: 'June'},
            {id: 7, name: 'July'},
            {id: 8, name: 'August'},
            {id: 9, name: 'Septermber'},
            {id: 10, name: 'October'},
            {id: 11, name: 'November'},
            {id: 12, name: 'December'}
        ],
        days_search: [
            {id: 'Lunes', title: 'Monday'},
            {id: 'Martes', title: 'Tuesday'},
            {id: 'Miercoles', title: 'Wednesday'},
            {id: 'Jueves', title: 'Thursday'},
            {id: 'Viernes', title: 'Friday'},
            {id: 'Sabado', title: 'Saturday'},
            {id: 'Domingo', title: 'Sunday'}
        ],
        preregister_header: 'La <span class="red">FLAT RARE OF DISCOUNTS</span> <br> to 50% and 2×1 in restaurants, <br> activities for spare time <br> and entrance to discotheque. <br><br><br> <span class="red">¡DEP OFFER!</span> <br><br>',
        preregister_pruebalo: 'TRY IT FOR ONE YEAR ONLY',
        preregister_price_now: 'NOW 39€ YEAR',
        preregister_already_user: 'If you already member',
        preregister_click_here: 'click here',
        login_cvc_required: 'CVV is required',
        hazte_socio: 'BELONGS TO MEMBER',
        descuentos: 'DISCOUNTS',
        recibir_notificaciones: 'Turn on notifications',
        dejar_notificaciones: 'Turn off notifications',
        your_city: 'YOUR CITY',
        eres_socio: 'ALREADY MEMBER?',
        introduce_email: 'Enter your email that you put in the registration:',
        validar_registro: 'VALIDATE MY REGISTRY',
        si_socio: 'YES, CONGRATULATIONS!',
        end_subscription: 'Subscription finish date',
        renew_subscription: 'RENEW FOR ONE YEAR MORE 39€',
        reservar: 'BOOK',
        reservado: 'BOOKED',
        hazte_socio: 'MAKE MEMBER',
        info: 'INFO',
        condiciones: 'CONDITIONS',
        donde: 'WHERE?',
        como_reservar: 'HOW TO BOOK?',
        localizacion: 'LOCATION',
        llamar: 'CALL',
        lo_quiero: 'I WANT IT',
        lo_quiero_invitado: 'MAKE MEMBER AND GET THIS DISCOUNT',
        canjear_plan: 'EXCHANGE PLAN',
        menssage: 'Message',
        estas_seguro: 'Only the person in charge of the premises must validate the plan. If you validate it without being in the establishment, you lose the plan. Are you in charge of the premises?',
        canjear: 'EXCHANGE',
        direccion: 'ADDRESS'
    },
    es: {
        yes: 'Si',
        no: 'No',
        confirmation: 'Confirmación',
        name_required: 'Nombre es requerido',
        email_required: 'Email es requerido',
        email_invalid: 'Email es inválido',
        password_required: 'Password es requerido',
        password_old_required: 'Contraseña anterior es requerida',
        message: 'Mensage',
        login: 'Ingresar',
        email: 'Email',
        password: 'Contraseña',
        there_was_an_error: 'Ocurrio un problema al cargar los datos',
        are_sure_to_logout: 'Esta seguro que quieres salir ?',
        today: 'Hoy',
        all: 'Todas',
        welcome: 'Bienvenido',
        meetings: 'Mis Reuniones',
        profile: 'Perfil',
        back: 'Atras',
        call_to: 'Llamar',
        send_email: 'Enviar email',
        acceso_socios: 'ACCESO SOCIOS',
        login_msg1: 'Introduce el email que usaste <br> en el registro.',
        login_msg2: 'ADVERTENCIA sólo puedes usar tu <br> suscripción en un dispositivo',
        no_socios: 'NO SOCIOS',
        login_msg3: 'Aún no soy socio, pero quiero entrar <br> como invitado y ver los descuentos',
        invitado: 'INVITADO',
        entrar: 'ENTRAR',
        login_email_required: 'Email es requerido',
        login_email_invalid: 'Email es inválido',
        nombre: 'Nombre',
        apellido: 'Apellido',
        Email: 'Email',
        tarjeta: 'Nº tajeta',
        cvc: 'CVV',
        mes: 'Mes',
        ano: 'Año',
        enviar: 'ENVIAR',
        acepto: 'Acepto las condiciones y el aviso legal',
        register_header: 'FORMULARIO DE REGISTRO <br> Rellena este formulario para entrar <br> en el club más exclusivo de descuentos',
        renew_header: 'FORMULARIO DE PAGO <br> Rellena este formulario para continuar <br> en el club más exclusivo de descuentos',
        login_nombre_required: 'Nombre es requerido',
        login_apellido_required: 'Apellido es requerido',
        login_tarjeta_required: 'Tarjeta es requerido',
        login_mes_required: 'Mes es requerido',
        login_ano_required: 'Año es requerido',
        login_acepto_required: 'Debes aceptar los terminos y condiciones',
        login_cvc_required: 'CVV es requerido',
        months: [
            {id: 1, name: 'January'},
            {id: 2, name: 'February'},
            {id: 3, name: 'March'},
            {id: 4, name: 'April'},
            {id: 5, name: 'May'},
            {id: 6, name: 'June'},
            {id: 7, name: 'July'},
            {id: 8, name: 'August'},
            {id: 9, name: 'Septermber'},
            {id: 10, name: 'October'},
            {id: 11, name: 'November'},
            {id: 12, name: 'December'}
        ],
        days_search: [
            {id: 'Lunes', title: 'Lunes'},
            {id: 'Martes', title: 'Martes'},
            {id: 'Miercoles', title: 'Miercoles'},
            {id: 'Jueves', title: 'Jueves'},
            {id: 'Viernes', title: 'Viernes'},
            {id: 'Sabado', title: 'Sabado'},
            {id: 'Domingo', title: 'Domingo'}
        ],
        preregister_header: 'La <span class="red">TARIFA PLANA DE DESCUENTOS</span> <br> hasta el 50% y 2×1 en restaurantes, <br> actividades de ocio <br> y entradas a discotecas. <br><br><br> <span class="red">¡OFERTA LANZAMIENTO!</span> <br><br>',
        preregister_pruebalo: 'PRUÉBALO 1 AÑO POR SÓLO',
        preregister_price_now: 'AHORA 39€ AÑO',
        preregister_already_user: 'Si ya eres socio haz',
        preregister_click_here: 'clic aquí',
        hazte_socio: 'HASTE SOCIO',
        descuentos: 'DESCUENTOS',
        recibir_notificaciones: 'Recibir notificaciones',
        dejar_notificaciones: 'Dejar de recibir notificaciones',
        your_city: 'TU CIUDAD',
        eres_socio: '¿ERES SOCIO?',
        introduce_email: 'Introduce el email que usaste en el registro:',
        validar_registro: 'VALIDAR MI REGISTRO',
        si_socio: '¡SÍ, ENHORABUENA!',
        end_subscription: 'Tu suscripción acaba el',
        renew_subscription: 'RENOVAR UN AÑO MÁS POR 39€',
        reservar: 'RESERVAR',
        reservado: 'RESERVADO',
        hazte_socio: 'HAZTE SOCIO',
        info: 'INFO',
        condiciones: 'CONDICIONES',
        donde: '¿DÓNDE?',
        como_reservar: '¿CÓMO RESERVAR?',
        localizacion: 'LOCALIZACIÓN',
        llamar: 'LLAMAR',
        lo_quiero: 'LO QUIERO',
        lo_quiero_invitado: 'HAZTE SOCIO Y CONSIGUE ESTE DESCUENTO',
        canjear_plan: 'CANJEAR PLAN',
        menssage: 'Mensaje',
        estas_seguro: 'Solo el responsable del local debe validar el plan. Si lo validas sin estar en el establecimiento pierdes el plan. ¿Eres el responsable del local?',
        canjear: 'CANJEAR',
        direccion: 'DIRECCIÓN'
    }
};

function t(label) {

    if (lang[applicationLanguage][label] == undefined) {
        return label;
    } else {
        return lang[applicationLanguage][label]
    }
}

function updateLanguage(l) {

    applicationLanguage = l;

    /*
    if (scopeLogin != undefined) {

        scopeLogin.labels = lang[applicationLanguage];
        scopeLogin.$apply();
    }

    if (scopeMeetings != undefined) {

        scopeMeetings.labels = lang[applicationLanguage];
        scopeMeetings.$apply();
    }*/

    moment.locale(applicationLanguage);

    localStorage.setItem('lang', applicationLanguage);
}